"""
Seed script — 16 Area Intelligence records across Riyadh, Jeddah and Dammam.

Exported from local development database on 2026-06-29.
Safe to re-run: existing records are updated in-place (upsert on area_name + city).

Run from the backend/ directory:
    python seed_areas.py

Or via Docker on the server:
    docker compose -f docker-compose.prod.yml exec backend python seed_areas.py
"""

import sys
import os

sys.path.insert(0, os.path.dirname(__file__))

from sqlalchemy import select
from app.db.session import SessionLocal
import app.models  # noqa: F401 — registers all models
from app.models.area_intelligence import AreaIntelligence

AREAS = [
    {
        "area_name": "Al Faisaliyah",
        "city": "Dammam",
        "center_lat": 26.428,
        "center_lng": 50.098,
        "commute_minutes_to_center": 9,
        "school_score": 72.9,
        "healthcare_score": 77.2,
        "lifestyle_score": 73.0,
        "traffic_score": 95.0,
        "family_score": 77.5,
        "area_score": 79.5,
        "tags": ["Affordable", "Family Friendly"],
        "overview": "Affordable family district close to Aramco corridor with quick highway access.",
        "market_notes": ["Aramco contractor demand pushing 3BR rents."],
        "rent_trend": [
            {"year": "2021", "avg_rent_annual": 68000},
            {"year": "2022", "avg_rent_annual": 72000},
            {"year": "2023", "avg_rent_annual": 78000},
            {"year": "2024", "avg_rent_annual": 82000},
            {"year": "2025", "avg_rent_annual": 86000},
        ],
        "schools": [{"name": "Al Muna International School for Boys", "type": "International", "rating": 0, "distance_km": 0.44}, {"name": "Secondary Development Private Schools Benin", "type": "Public", "rating": 0, "distance_km": 1.06}, {"name": "Victory International Schools Dammam", "type": "International", "rating": 0, "distance_km": 0.42}, {"name": "Bangladesh International School Dammam", "type": "International", "rating": 0, "distance_km": 1.21}, {"name": "International Future School, Dammam", "type": "International", "rating": 0, "distance_km": 1.37}, {"name": "Excellence International school - boys section", "type": "International", "rating": 0, "distance_km": 2.32}],
        "hospitals": [{"name": "King Fahad Specialist Hospital - Dammam.", "tier": "Specialty", "rating": 3.9, "distance_km": 1.72}, {"name": "Almana Hospital Dammam", "tier": "General", "rating": 4.0, "distance_km": 2.44}, {"name": "Saud Al Babtain Cardiac Center", "tier": "General", "rating": 4.1, "distance_km": 1.5}, {"name": "Dammam Medical Complex", "tier": "General", "rating": 3.4, "distance_km": 1.47}],
        "lifestyle": {"gyms": {"count": 13, "avg_rating": 3.8}, "malls": {"count": 20, "avg_rating": 3.5}, "parks": {"count": 20, "avg_rating": 3.5}, "restaurants": {"count": 20, "avg_rating": 3.8}},
    },
    {
        "area_name": "University District",
        "city": "Dammam",
        "center_lat": 26.362,
        "center_lng": 50.128,
        "commute_minutes_to_center": 9,
        "school_score": 68.9,
        "healthcare_score": 61.8,
        "lifestyle_score": 73.0,
        "traffic_score": 95.0,
        "family_score": 71.5,
        "area_score": 74.5,
        "tags": ["Student Area", "Affordable"],
        "overview": "Adjacent to IAU campus — student rentals, studios and shared apartments dominate supply.",
        "market_notes": ["Seasonal: 70% turnover at academic year start."],
        "rent_trend": [
            {"year": "2021", "avg_rent_annual": 44000},
            {"year": "2022", "avg_rent_annual": 46000},
            {"year": "2023", "avg_rent_annual": 48000},
            {"year": "2024", "avg_rent_annual": 50000},
            {"year": "2025", "avg_rent_annual": 52000},
        ],
        "schools": [{"name": "Yarmook Elementary Private School", "type": "Public", "rating": 0, "distance_km": 0.55}, {"name": "Dhahran General Hospital", "type": "Public", "rating": 0, "distance_km": 0.55}],
        "hospitals": [{"name": "Dhahran General Hospital", "tier": "General", "rating": 3.2, "distance_km": 2.26}, {"name": "Eye Specialist Hospital", "tier": "Specialty", "rating": 3.5, "distance_km": 2.35}],
        "lifestyle": {"gyms": {"count": 8, "avg_rating": 3.1}, "malls": {"count": 20, "avg_rating": 3.9}, "parks": {"count": 20, "avg_rating": 3.1}, "restaurants": {"count": 20, "avg_rating": 4.3}},
    },
    {
        "area_name": "Al Rawdah",
        "city": "Jeddah",
        "center_lat": 21.558,
        "center_lng": 39.135,
        "commute_minutes_to_center": 25,
        "school_score": 77.2,
        "healthcare_score": 93.0,
        "lifestyle_score": 73.0,
        "traffic_score": 78.0,
        "family_score": 81.2,
        "area_score": 80.5,
        "tags": ["Family Friendly", "Affordable"],
        "overview": "Mid-market Jeddah favourite — strong school catchment and easy corniche access.",
        "market_notes": ["Family demand outpacing supply for 4BR villas."],
        "rent_trend": [
            {"year": "2021", "avg_rent_annual": 102000},
            {"year": "2022", "avg_rent_annual": 108000},
            {"year": "2023", "avg_rent_annual": 115000},
            {"year": "2024", "avg_rent_annual": 119000},
            {"year": "2025", "avg_rent_annual": 124000},
        ],
        "schools": [{"name": "Jeddah International School", "type": "International", "rating": 0, "distance_km": 0.42}, {"name": "Building Blocks International School", "type": "International", "rating": 0, "distance_km": 1.36}, {"name": "King Faisal Specialist Hospital & Research Centre, Jeddah", "type": "International", "rating": 0, "distance_km": 1.35}],
        "hospitals": [{"name": "King Faisal Specialist Hospital & Research Centre, Jeddah", "tier": "Specialty", "rating": 4.0, "distance_km": 1.35}, {"name": "Dr. Samir Abbas Hospital", "tier": "General", "rating": 4.3, "distance_km": 1.19}, {"name": "King Fahad Armed Forces Hospital", "tier": "General", "rating": 3.5, "distance_km": 1.89}],
        "lifestyle": {"gyms": {"count": 20, "avg_rating": 3.9}, "malls": {"count": 20, "avg_rating": 3.9}, "parks": {"count": 20, "avg_rating": 3.3}, "restaurants": {"count": 20, "avg_rating": 4.2}},
    },
    {
        "area_name": "Al Shati",
        "city": "Jeddah",
        "center_lat": 21.599,
        "center_lng": 39.108,
        "commute_minutes_to_center": 28,
        "school_score": 74.9,
        "healthcare_score": 82.8,
        "lifestyle_score": 73.0,
        "traffic_score": 78.0,
        "family_score": 77.4,
        "area_score": 77.3,
        "tags": ["Family Friendly", "Luxury"],
        "overview": "Coastal villa & townhouse district with private beach access and corniche frontage.",
        "market_notes": ["Seasonal premium during summer holidays."],
        "rent_trend": [
            {"year": "2021", "avg_rent_annual": 142000},
            {"year": "2022", "avg_rent_annual": 150000},
            {"year": "2023", "avg_rent_annual": 158000},
            {"year": "2024", "avg_rent_annual": 162000},
            {"year": "2025", "avg_rent_annual": 168000},
        ],
        "schools": [{"name": "Al Moktashef International School", "type": "International", "rating": 0, "distance_km": 1.29}, {"name": "Jeddah International Turkish School", "type": "International", "rating": 0, "distance_km": 2.52}],
        "hospitals": [{"name": "Saudi German Hospital - Jeddah", "tier": "General", "rating": 3.3, "distance_km": 2.6}, {"name": "مستشفى الدكتور سليمان فقيه", "tier": "General", "rating": 3.2, "distance_km": 0.37}],
        "lifestyle": {"gyms": {"count": 20, "avg_rating": 4.5}, "malls": {"count": 20, "avg_rating": 3.6}, "parks": {"count": 20, "avg_rating": 4.1}, "restaurants": {"count": 20, "avg_rating": 4.0}},
    },
    {
        "area_name": "Al Faisaliyah",
        "city": "Riyadh",
        "center_lat": 24.6904,
        "center_lng": 46.6849,
        "commute_minutes_to_center": 15,
        "school_score": 72.4,
        "healthcare_score": 82.8,
        "lifestyle_score": 73.0,
        "traffic_score": 95.0,
        "family_score": 79.0,
        "area_score": 80.8,
        "tags": ["Business Hub"],
        "overview": "Central Riyadh district anchored by Al Faisaliyah Tower — prime location for business and upscale living.",
        "market_notes": [],
        "rent_trend": [
            {"year": "2021", "avg_rent_annual": 144000},
            {"year": "2022", "avg_rent_annual": 150000},
            {"year": "2023", "avg_rent_annual": 158000},
            {"year": "2024", "avg_rent_annual": 165000},
            {"year": "2025", "avg_rent_annual": 170000},
        ],
        "schools": [{"name": "Victory Pioneers International Schools", "type": "International", "rating": 0, "distance_km": 1.24}, {"name": "Al Rissalah International Schools", "type": "International", "rating": 0, "distance_km": 2.11}],
        "hospitals": [{"name": "Al Hammadi Hospital Al Olaya", "tier": "General", "rating": 3.4, "distance_km": 2.19}, {"name": "Dr. Sulaiman Al Habib Olaya Medical Complex", "tier": "General", "rating": 4.6, "distance_km": 1.72}, {"name": "Dr. Talal Merdad Medical Center", "tier": "Specialty", "rating": 4.6, "distance_km": 1.6}],
        "lifestyle": {"gyms": {"count": 20, "avg_rating": 4.4}, "malls": {"count": 20, "avg_rating": 3.5}, "parks": {"count": 20, "avg_rating": 3.2}, "restaurants": {"count": 20, "avg_rating": 4.1}},
    },
    {
        "area_name": "Al Malqa",
        "city": "Riyadh",
        "center_lat": 24.81,
        "center_lng": 46.637,
        "commute_minutes_to_center": 22,
        "school_score": 76.2,
        "healthcare_score": 82.8,
        "lifestyle_score": 73.0,
        "traffic_score": 78.0,
        "family_score": 77.8,
        "area_score": 77.7,
        "tags": ["Luxury", "Family Friendly"],
        "overview": "Premium compounds, embassies and elite schools. Lower turnover with sticky long-term tenants.",
        "market_notes": ["Premium compound waitlists 4-6 months.", "Traffic congestion on King Salman Rd peak hours."],
        "rent_trend": [
            {"year": "2021", "avg_rent_annual": 152000},
            {"year": "2022", "avg_rent_annual": 160000},
            {"year": "2023", "avg_rent_annual": 168000},
            {"year": "2024", "avg_rent_annual": 172000},
            {"year": "2025", "avg_rent_annual": 178000},
        ],
        "schools": [{"name": "Rowad AlKhaleej International Schools in Riyadh", "type": "International", "rating": 0, "distance_km": 1.09}, {"name": "Educational Age International Schools", "type": "International", "rating": 0, "distance_km": 1.69}],
        "hospitals": [{"name": "Kingdom Hospital", "tier": "General", "rating": 3.2, "distance_km": 2.0}, {"name": "Saudi German Hospital Riyadh - SGH", "tier": "General", "rating": 3.3, "distance_km": 1.39}, {"name": "Nabd Alyasmin Polyclinic", "tier": "General", "rating": 4.1, "distance_km": 0.25}],
        "lifestyle": {"gyms": {"count": 20, "avg_rating": 4.1}, "malls": {"count": 20, "avg_rating": 3.9}, "parks": {"count": 20, "avg_rating": 4.0}, "restaurants": {"count": 20, "avg_rating": 4.1}},
    },
    {
        "area_name": "Al Nakheel",
        "city": "Riyadh",
        "center_lat": 24.7985,
        "center_lng": 46.6795,
        "commute_minutes_to_center": 18,
        "school_score": 80.9,
        "healthcare_score": 79.3,
        "lifestyle_score": 73.0,
        "traffic_score": 88.0,
        "family_score": 79.9,
        "area_score": 80.7,
        "tags": ["Family Friendly"],
        "overview": "Established residential district in northern Riyadh with good school access and quiet streets.",
        "market_notes": [],
        "rent_trend": [
            {"year": "2021", "avg_rent_annual": 108000},
            {"year": "2022", "avg_rent_annual": 115000},
            {"year": "2023", "avg_rent_annual": 120000},
            {"year": "2024", "avg_rent_annual": 124000},
            {"year": "2025", "avg_rent_annual": 128000},
        ],
        "schools": [{"name": "Ecole Francaise Internationale de Riyadh", "type": "International", "rating": 3.7, "distance_km": 1.24}, {"name": "Kingdom International Schools", "type": "International", "rating": 0, "distance_km": 2.3}],
        "hospitals": [{"name": "Kingdom Hospital", "tier": "General", "rating": 3.2, "distance_km": 2.56}, {"name": "Surgca Medical Center", "tier": "Specialty", "rating": 4.1, "distance_km": 0.51}, {"name": "مجمع مايا الطبي الرياض MAYA CLINIC", "tier": "General", "rating": 4.3, "distance_km": 0.4}],
        "lifestyle": {"gyms": {"count": 20, "avg_rating": 4.5}, "malls": {"count": 20, "avg_rating": 4.0}, "parks": {"count": 20, "avg_rating": 3.5}, "restaurants": {"count": 20, "avg_rating": 3.7}},
    },
    {
        "area_name": "Al Narjis",
        "city": "Riyadh",
        "center_lat": 24.845,
        "center_lng": 46.692,
        "commute_minutes_to_center": 27,
        "school_score": 64.2,
        "healthcare_score": 79.3,
        "lifestyle_score": 68.5,
        "traffic_score": 78.0,
        "family_score": 71.7,
        "area_score": 72.3,
        "tags": ["Family Friendly", "Affordable"],
        "overview": "Best-value family district in north Riyadh. Strong rental yield with rapid infrastructure rollout.",
        "market_notes": ["Highest YoY rent growth in North Riyadh corridor.", "Watch: new metro feeder bus line opening Q3."],
        "rent_trend": [
            {"year": "2021", "avg_rent_annual": 74000},
            {"year": "2022", "avg_rent_annual": 82000},
            {"year": "2023", "avg_rent_annual": 88000},
            {"year": "2024", "avg_rent_annual": 93000},
            {"year": "2025", "avg_rent_annual": 98000},
        ],
        "schools": [{"name": "Dar Al Bra'ah Schools", "type": "Public", "rating": 4.0, "distance_km": 2.43}],
        "hospitals": [{"name": "Narjis Primary Healthcare Clinic", "tier": "General", "rating": 3.3, "distance_km": 1.16}, {"name": "kfshrc", "tier": "General", "rating": 4.6, "distance_km": 1.79}, {"name": "Hope Abilitation Medical Center", "tier": "Specialty", "rating": 4.7, "distance_km": 2.64}],
        "lifestyle": {"gyms": {"count": 3, "avg_rating": 2.7}, "malls": {"count": 20, "avg_rating": 3.7}, "parks": {"count": 15, "avg_rating": 3.2}, "restaurants": {"count": 20, "avg_rating": 4.2}},
    },
    {
        "area_name": "Al Olaya",
        "city": "Riyadh",
        "center_lat": 24.695,
        "center_lng": 46.686,
        "commute_minutes_to_center": 15,
        "school_score": 72.4,
        "healthcare_score": 79.8,
        "lifestyle_score": 73.0,
        "traffic_score": 95.0,
        "family_score": 78.1,
        "area_score": 80.0,
        "tags": ["Business Hub", "Walkable"],
        "overview": "Central business spine with strong professional tenant base and metro access.",
        "market_notes": ["Demand led by corporate relocations.", "Studio + 1BR vacancy compressing."],
        "rent_trend": [
            {"year": "2021", "avg_rent_annual": 132000},
            {"year": "2022", "avg_rent_annual": 136000},
            {"year": "2023", "avg_rent_annual": 140000},
            {"year": "2024", "avg_rent_annual": 142000},
            {"year": "2025", "avg_rent_annual": 145000},
        ],
        "schools": [{"name": "Al Rissalah International Schools", "type": "International", "rating": 0, "distance_km": 1.58}, {"name": "Palm Crest International School", "type": "International", "rating": 0, "distance_km": 2.24}],
        "hospitals": [{"name": "Al Hammadi Hospital Al Olaya", "tier": "General", "rating": 3.4, "distance_km": 1.71}, {"name": "Dr. Sulaiman Al Habib Olaya Medical Complex", "tier": "General", "rating": 4.6, "distance_km": 1.36}, {"name": "CARE MEDICAL CENTER", "tier": "General", "rating": 4.3, "distance_km": 1.53}],
        "lifestyle": {"gyms": {"count": 20, "avg_rating": 4.2}, "malls": {"count": 20, "avg_rating": 3.7}, "parks": {"count": 20, "avg_rating": 3.3}, "restaurants": {"count": 20, "avg_rating": 4.2}},
    },
    {
        "area_name": "Al Rawdah",
        "city": "Riyadh",
        "center_lat": 24.7803,
        "center_lng": 46.7224,
        "commute_minutes_to_center": 15,
        "school_score": 75.4,
        "healthcare_score": 61.7,
        "lifestyle_score": 73.0,
        "traffic_score": 95.0,
        "family_score": 73.8,
        "area_score": 76.4,
        "tags": ["Family Friendly"],
        "overview": "Mature residential district in northeast Riyadh with strong community infrastructure and stable rents.",
        "market_notes": [],
        "rent_trend": [
            {"year": "2021", "avg_rent_annual": 90000},
            {"year": "2022", "avg_rent_annual": 95000},
            {"year": "2023", "avg_rent_annual": 100000},
            {"year": "2024", "avg_rent_annual": 104000},
            {"year": "2025", "avg_rent_annual": 108000},
        ],
        "schools": [{"name": "British International School Riyadh Al Hamra Campus", "type": "International", "rating": 0, "distance_km": 1.46}, {"name": "Dar Alshewaifat International Schools", "type": "International", "rating": 0, "distance_km": 0.19}],
        "hospitals": [{"name": "Mouwasat Hospital", "tier": "General", "rating": 2.7, "distance_km": 1.29}, {"name": "Riyadh Hospital", "tier": "General", "rating": 4.0, "distance_km": 2.86}],
        "lifestyle": {"gyms": {"count": 20, "avg_rating": 4.1}, "malls": {"count": 20, "avg_rating": 3.6}, "parks": {"count": 20, "avg_rating": 3.7}, "restaurants": {"count": 20, "avg_rating": 3.8}},
    },
    {
        "area_name": "Al Sahafah",
        "city": "Riyadh",
        "center_lat": 24.7711,
        "center_lng": 46.6455,
        "commute_minutes_to_center": 21,
        "school_score": 72.4,
        "healthcare_score": 78.2,
        "lifestyle_score": 73.0,
        "traffic_score": 78.0,
        "family_score": 75.1,
        "area_score": 75.4,
        "tags": ["Affordable"],
        "overview": "Affordable mid-density neighbourhood in northwest Riyadh, popular with mid-income families.",
        "market_notes": [],
        "rent_trend": [
            {"year": "2021", "avg_rent_annual": 72000},
            {"year": "2022", "avg_rent_annual": 76000},
            {"year": "2023", "avg_rent_annual": 80000},
            {"year": "2024", "avg_rent_annual": 83000},
            {"year": "2025", "avg_rent_annual": 86000},
        ],
        "schools": [{"name": "Dome International Schools", "type": "International", "rating": 3.7, "distance_km": 2.71}],
        "hospitals": [{"name": "Dallah Hospital", "tier": "General", "rating": 3.3, "distance_km": 2.75}, {"name": "Aseel Medical Center", "tier": "Specialty", "rating": 4.5, "distance_km": 1.56}],
        "lifestyle": {"gyms": {"count": 20, "avg_rating": 4.0}, "malls": {"count": 20, "avg_rating": 3.9}, "parks": {"count": 20, "avg_rating": 4.0}, "restaurants": {"count": 20, "avg_rating": 4.0}},
    },
    {
        "area_name": "Al Sulimaniyah",
        "city": "Riyadh",
        "center_lat": 24.6836,
        "center_lng": 46.6973,
        "commute_minutes_to_center": 7,
        "school_score": 72.4,
        "healthcare_score": 85.3,
        "lifestyle_score": 73.0,
        "traffic_score": 95.0,
        "family_score": 79.8,
        "area_score": 81.4,
        "tags": ["Business Hub"],
        "overview": "Central Riyadh business district with strong demand from professionals and corporate tenants.",
        "market_notes": [],
        "rent_trend": [
            {"year": "2021", "avg_rent_annual": 132000},
            {"year": "2022", "avg_rent_annual": 138000},
            {"year": "2023", "avg_rent_annual": 145000},
            {"year": "2024", "avg_rent_annual": 150000},
            {"year": "2025", "avg_rent_annual": 155000},
        ],
        "schools": [{"name": "Geniuses-of-knowledge-International-Schools", "type": "International", "rating": 0, "distance_km": 1.22}, {"name": "Palm Crest International School", "type": "International", "rating": 0, "distance_km": 1.93}],
        "hospitals": [{"name": "King Salman Heart Center", "tier": "General", "rating": 3.6, "distance_km": 0.8}, {"name": "CARE MEDICAL CENTER", "tier": "General", "rating": 4.3, "distance_km": 0.83}, {"name": "National Neuroscience Institute", "tier": "General", "rating": 5.0, "distance_km": 1.0}],
        "lifestyle": {"gyms": {"count": 20, "avg_rating": 4.4}, "malls": {"count": 20, "avg_rating": 3.9}, "parks": {"count": 20, "avg_rating": 3.3}, "restaurants": {"count": 20, "avg_rating": 4.0}},
    },
    {
        "area_name": "Al Yasmin",
        "city": "Riyadh",
        "center_lat": 24.823,
        "center_lng": 46.673,
        "commute_minutes_to_center": 19,
        "school_score": 60.6,
        "healthcare_score": 86.2,
        "lifestyle_score": 73.0,
        "traffic_score": 88.0,
        "family_score": 74.9,
        "area_score": 76.3,
        "tags": ["Family Friendly", "Luxury"],
        "overview": "Premium north Riyadh district with mature compounds, top-rated international schools and strong family demand.",
        "market_notes": ["Compound supply tightening — vacancy under 4%.", "Top performer for 3+ bedroom family rentals."],
        "rent_trend": [
            {"year": "2021", "avg_rent_annual": 108000},
            {"year": "2022", "avg_rent_annual": 118000},
            {"year": "2023", "avg_rent_annual": 126000},
            {"year": "2024", "avg_rent_annual": 130000},
            {"year": "2025", "avg_rent_annual": 135000},
        ],
        "schools": [{"name": "Alssadarah Schools", "type": "Public", "rating": 0, "distance_km": 1.31}, {"name": "Dar Al Bra'ah Schools", "type": "Public", "rating": 4.0, "distance_km": 2.28}],
        "hospitals": [{"name": "kfshrc", "tier": "General", "rating": 4.6, "distance_km": 2.17}, {"name": "Hope Abilitation Medical Center", "tier": "Specialty", "rating": 4.7, "distance_km": 0.82}, {"name": "Elevate Clinic", "tier": "General", "rating": 4.6, "distance_km": 1.23}],
        "lifestyle": {"gyms": {"count": 13, "avg_rating": 4.2}, "malls": {"count": 20, "avg_rating": 3.7}, "parks": {"count": 20, "avg_rating": 3.9}, "restaurants": {"count": 20, "avg_rating": 4.0}},
    },
    {
        "area_name": "Diplomatic Quarter",
        "city": "Riyadh",
        "center_lat": 24.6942,
        "center_lng": 46.6158,
        "commute_minutes_to_center": 14,
        "school_score": 63.9,
        "healthcare_score": 83.0,
        "lifestyle_score": 73.0,
        "traffic_score": 95.0,
        "family_score": 76.1,
        "area_score": 78.3,
        "tags": ["Luxury"],
        "overview": "Exclusive gated enclave housing embassies and high-end compounds — the most premium address in Riyadh.",
        "market_notes": [],
        "rent_trend": [
            {"year": "2021", "avg_rent_annual": 180000},
            {"year": "2022", "avg_rent_annual": 190000},
            {"year": "2023", "avg_rent_annual": 200000},
            {"year": "2024", "avg_rent_annual": 210000},
            {"year": "2025", "avg_rent_annual": 220000},
        ],
        "schools": [{"name": "King Faisal School", "type": "Public", "rating": 0, "distance_km": 1.26}, {"name": "Beech Hall School Riyadh", "type": "Public", "rating": 0, "distance_km": 1.2}],
        "hospitals": [{"name": "King Khaled Eye Specialist Hospital", "tier": "Specialty", "rating": 4.1, "distance_km": 2.08}, {"name": "InterHealth Hospital", "tier": "General", "rating": 3.3, "distance_km": 1.83}],
        "lifestyle": {"gyms": {"count": 11, "avg_rating": 4.1}, "malls": {"count": 20, "avg_rating": 4.1}, "parks": {"count": 20, "avg_rating": 3.4}, "restaurants": {"count": 20, "avg_rating": 3.9}},
    },
    {
        "area_name": "Hitteen",
        "city": "Riyadh",
        "center_lat": 24.8175,
        "center_lng": 46.6502,
        "commute_minutes_to_center": 20,
        "school_score": 76.4,
        "healthcare_score": 77.2,
        "lifestyle_score": 73.0,
        "traffic_score": 88.0,
        "family_score": 77.7,
        "area_score": 78.8,
        "tags": ["Family Friendly"],
        "overview": "Growing north Riyadh district with new developments, good schools, and family-oriented community feel.",
        "market_notes": [],
        "rent_trend": [
            {"year": "2021", "avg_rent_annual": 96000},
            {"year": "2022", "avg_rent_annual": 102000},
            {"year": "2023", "avg_rent_annual": 108000},
            {"year": "2024", "avg_rent_annual": 112000},
            {"year": "2025", "avg_rent_annual": 116000},
        ],
        "schools": [{"name": "Rowad AlKhaleej International Schools in Riyadh", "type": "International", "rating": 0, "distance_km": 1.84}, {"name": "Educational Age International Schools", "type": "International", "rating": 0, "distance_km": 2.77}],
        "hospitals": [{"name": "Kingdom Hospital", "tier": "General", "rating": 3.2, "distance_km": 1.86}, {"name": "Nabd Alyasmin Polyclinic", "tier": "General", "rating": 4.1, "distance_km": 1.6}],
        "lifestyle": {"gyms": {"count": 20, "avg_rating": 3.9}, "malls": {"count": 20, "avg_rating": 3.9}, "parks": {"count": 20, "avg_rating": 4.0}, "restaurants": {"count": 20, "avg_rating": 4.1}},
    },
    {
        "area_name": "Qurtuba",
        "city": "Riyadh",
        "center_lat": 24.7732,
        "center_lng": 46.6233,
        "commute_minutes_to_center": 22,
        "school_score": 68.2,
        "healthcare_score": 78.0,
        "lifestyle_score": 73.0,
        "traffic_score": 78.0,
        "family_score": 73.6,
        "area_score": 74.1,
        "tags": ["Affordable"],
        "overview": "Well-connected northwest Riyadh neighbourhood with affordable villas and easy King Abdullah Road access.",
        "market_notes": [],
        "rent_trend": [
            {"year": "2021", "avg_rent_annual": 84000},
            {"year": "2022", "avg_rent_annual": 88000},
            {"year": "2023", "avg_rent_annual": 92000},
            {"year": "2024", "avg_rent_annual": 96000},
            {"year": "2025", "avg_rent_annual": 99000},
        ],
        "schools": [{"name": "Little Elites", "type": "Public", "rating": 4.6, "distance_km": 0.07}],
        "hospitals": [{"name": "Aseel Medical Center", "tier": "Specialty", "rating": 4.5, "distance_km": 0.74}],
        "lifestyle": {"gyms": {"count": 20, "avg_rating": 3.9}, "malls": {"count": 20, "avg_rating": 3.6}, "parks": {"count": 20, "avg_rating": 3.8}, "restaurants": {"count": 20, "avg_rating": 4.1}},
    },
]


def seed():
    db = SessionLocal()
    inserted = 0
    updated = 0
    try:
        for data in AREAS:
            existing = db.scalars(
                select(AreaIntelligence).where(
                    AreaIntelligence.area_name == data["area_name"],
                    AreaIntelligence.city == data["city"],
                )
            ).first()

            if existing:
                for key, value in data.items():
                    setattr(existing, key, value)
                updated += 1
            else:
                db.add(AreaIntelligence(**data))
                inserted += 1

        db.commit()
        print(f"Area intelligence seed complete — {inserted} inserted, {updated} updated.")
    except Exception as exc:
        db.rollback()
        print(f"Seed failed: {exc}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()
