/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedSearchesRouteImport } from './routes/saved-searches'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as PropertyRequestsRouteImport } from './routes/property-requests'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotificationSettingsRouteImport } from './routes/notification-settings'
import { Route as MyLeadsRouteImport } from './routes/my-leads'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as ImportRouteImport } from './routes/import'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as PropertyRequestsNewRouteImport } from './routes/property-requests.new'
import { Route as PropertyRequestsIdRouteImport } from './routes/property-requests.$id'
import { Route as PartnerRequestsRouteImport } from './routes/partner.requests'
import { Route as PartnerRegisterRouteImport } from './routes/partner.register'
import { Route as LeadNewRouteImport } from './routes/lead.new'
import { Route as LeadLeadIdRouteImport } from './routes/lead.$leadId'
import { Route as ContractLeadIdRouteImport } from './routes/contract.$leadId'
import { Route as AgentIdRouteImport } from './routes/agent.$id'
import { Route as AdminPropertyRequestsRouteImport } from './routes/admin_.property-requests'
import { Route as AdminNotificationsRouteImport } from './routes/admin_.notifications'
import { Route as PropertyRouteImport } from './routes/property.'
import { Route as PartnerRequestsIdRouteImport } from './routes/partner.requests.$id'
import { Route as PartnerLeadsLeadIdRouteImport } from './routes/partner.leads.$leadId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedSearchesRoute = SavedSearchesRouteImport.update({
  id: '/saved-searches',
  path: '/saved-searches',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyRequestsRoute = PropertyRequestsRouteImport.update({
  id: '/property-requests',
  path: '/property-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationSettingsRoute = NotificationSettingsRouteImport.update({
  id: '/notification-settings',
  path: '/notification-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLeadsRoute = MyLeadsRouteImport.update({
  id: '/my-leads',
  path: '/my-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyRequestsNewRoute = PropertyRequestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PropertyRequestsRoute,
} as any)
const PropertyRequestsIdRoute = PropertyRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertyRequestsRoute,
} as any)
const PartnerRequestsRoute = PartnerRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerRegisterRoute = PartnerRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PartnerRoute,
} as any)
const LeadNewRoute = LeadNewRouteImport.update({
  id: '/lead/new',
  path: '/lead/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadLeadIdRoute = LeadLeadIdRouteImport.update({
  id: '/lead/$leadId',
  path: '/lead/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractLeadIdRoute = ContractLeadIdRouteImport.update({
  id: '/contract/$leadId',
  path: '/contract/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIdRoute = AgentIdRouteImport.update({
  id: '/agent/$id',
  path: '/agent/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropertyRequestsRoute = AdminPropertyRequestsRouteImport.update({
  id: '/admin_/property-requests',
  path: '/admin/property-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin_/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyRoute = PropertyRouteImport.update({
  id: '/property/',
  path: '/property/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRequestsIdRoute = PartnerRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PartnerRequestsRoute,
} as any)
const PartnerLeadsLeadIdRoute = PartnerLeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => PartnerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/areas': typeof AreasRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/estimate': typeof EstimateRoute
  '/import': typeof ImportRoute
  '/methodology': typeof MethodologyRoute
  '/my-leads': typeof MyLeadsRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/notifications': typeof NotificationsRoute
  '/partner': typeof PartnerRouteWithChildren
  '/partners': typeof PartnersRoute
  '/property-requests': typeof PropertyRequestsRouteWithChildren
  '/saved': typeof SavedRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/search': typeof SearchRoute
  '/property/': typeof PropertyRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/property-requests': typeof AdminPropertyRequestsRoute
  '/agent/$id': typeof AgentIdRoute
  '/contract/$leadId': typeof ContractLeadIdRoute
  '/lead/$leadId': typeof LeadLeadIdRoute
  '/lead/new': typeof LeadNewRoute
  '/partner/register': typeof PartnerRegisterRoute
  '/partner/requests': typeof PartnerRequestsRouteWithChildren
  '/property-requests/$id': typeof PropertyRequestsIdRoute
  '/property-requests/new': typeof PropertyRequestsNewRoute
  '/property/$id': typeof PropertyIdRoute
  '/partner/leads/$leadId': typeof PartnerLeadsLeadIdRoute
  '/partner/requests/$id': typeof PartnerRequestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/areas': typeof AreasRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/estimate': typeof EstimateRoute
  '/import': typeof ImportRoute
  '/methodology': typeof MethodologyRoute
  '/my-leads': typeof MyLeadsRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/notifications': typeof NotificationsRoute
  '/partner': typeof PartnerRouteWithChildren
  '/partners': typeof PartnersRoute
  '/property-requests': typeof PropertyRequestsRouteWithChildren
  '/saved': typeof SavedRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/search': typeof SearchRoute
  '/property': typeof PropertyRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/property-requests': typeof AdminPropertyRequestsRoute
  '/agent/$id': typeof AgentIdRoute
  '/contract/$leadId': typeof ContractLeadIdRoute
  '/lead/$leadId': typeof LeadLeadIdRoute
  '/lead/new': typeof LeadNewRoute
  '/partner/register': typeof PartnerRegisterRoute
  '/partner/requests': typeof PartnerRequestsRouteWithChildren
  '/property-requests/$id': typeof PropertyRequestsIdRoute
  '/property-requests/new': typeof PropertyRequestsNewRoute
  '/property/$id': typeof PropertyIdRoute
  '/partner/leads/$leadId': typeof PartnerLeadsLeadIdRoute
  '/partner/requests/$id': typeof PartnerRequestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/areas': typeof AreasRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/estimate': typeof EstimateRoute
  '/import': typeof ImportRoute
  '/methodology': typeof MethodologyRoute
  '/my-leads': typeof MyLeadsRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/notifications': typeof NotificationsRoute
  '/partner': typeof PartnerRouteWithChildren
  '/partners': typeof PartnersRoute
  '/property-requests': typeof PropertyRequestsRouteWithChildren
  '/saved': typeof SavedRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/search': typeof SearchRoute
  '/property/': typeof PropertyRoute
  '/admin_/notifications': typeof AdminNotificationsRoute
  '/admin_/property-requests': typeof AdminPropertyRequestsRoute
  '/agent/$id': typeof AgentIdRoute
  '/contract/$leadId': typeof ContractLeadIdRoute
  '/lead/$leadId': typeof LeadLeadIdRoute
  '/lead/new': typeof LeadNewRoute
  '/partner/register': typeof PartnerRegisterRoute
  '/partner/requests': typeof PartnerRequestsRouteWithChildren
  '/property-requests/$id': typeof PropertyRequestsIdRoute
  '/property-requests/new': typeof PropertyRequestsNewRoute
  '/property/$id': typeof PropertyIdRoute
  '/partner/leads/$leadId': typeof PartnerLeadsLeadIdRoute
  '/partner/requests/$id': typeof PartnerRequestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/advisor'
    | '/analytics'
    | '/areas'
    | '/auth'
    | '/compare'
    | '/estimate'
    | '/import'
    | '/methodology'
    | '/my-leads'
    | '/notification-settings'
    | '/notifications'
    | '/partner'
    | '/partners'
    | '/property-requests'
    | '/saved'
    | '/saved-searches'
    | '/search'
    | '/property/'
    | '/admin/notifications'
    | '/admin/property-requests'
    | '/agent/$id'
    | '/contract/$leadId'
    | '/lead/$leadId'
    | '/lead/new'
    | '/partner/register'
    | '/partner/requests'
    | '/property-requests/$id'
    | '/property-requests/new'
    | '/property/$id'
    | '/partner/leads/$leadId'
    | '/partner/requests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/advisor'
    | '/analytics'
    | '/areas'
    | '/auth'
    | '/compare'
    | '/estimate'
    | '/import'
    | '/methodology'
    | '/my-leads'
    | '/notification-settings'
    | '/notifications'
    | '/partner'
    | '/partners'
    | '/property-requests'
    | '/saved'
    | '/saved-searches'
    | '/search'
    | '/property'
    | '/admin/notifications'
    | '/admin/property-requests'
    | '/agent/$id'
    | '/contract/$leadId'
    | '/lead/$leadId'
    | '/lead/new'
    | '/partner/register'
    | '/partner/requests'
    | '/property-requests/$id'
    | '/property-requests/new'
    | '/property/$id'
    | '/partner/leads/$leadId'
    | '/partner/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/advisor'
    | '/analytics'
    | '/areas'
    | '/auth'
    | '/compare'
    | '/estimate'
    | '/import'
    | '/methodology'
    | '/my-leads'
    | '/notification-settings'
    | '/notifications'
    | '/partner'
    | '/partners'
    | '/property-requests'
    | '/saved'
    | '/saved-searches'
    | '/search'
    | '/property/'
    | '/admin_/notifications'
    | '/admin_/property-requests'
    | '/agent/$id'
    | '/contract/$leadId'
    | '/lead/$leadId'
    | '/lead/new'
    | '/partner/register'
    | '/partner/requests'
    | '/property-requests/$id'
    | '/property-requests/new'
    | '/property/$id'
    | '/partner/leads/$leadId'
    | '/partner/requests/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdvisorRoute: typeof AdvisorRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AreasRoute: typeof AreasRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  EstimateRoute: typeof EstimateRoute
  ImportRoute: typeof ImportRoute
  MethodologyRoute: typeof MethodologyRoute
  MyLeadsRoute: typeof MyLeadsRoute
  NotificationSettingsRoute: typeof NotificationSettingsRoute
  NotificationsRoute: typeof NotificationsRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  PartnersRoute: typeof PartnersRoute
  PropertyRequestsRoute: typeof PropertyRequestsRouteWithChildren
  SavedRoute: typeof SavedRoute
  SavedSearchesRoute: typeof SavedSearchesRoute
  SearchRoute: typeof SearchRoute
  PropertyRoute: typeof PropertyRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPropertyRequestsRoute: typeof AdminPropertyRequestsRoute
  AgentIdRoute: typeof AgentIdRoute
  ContractLeadIdRoute: typeof ContractLeadIdRoute
  LeadLeadIdRoute: typeof LeadLeadIdRoute
  LeadNewRoute: typeof LeadNewRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-searches': {
      id: '/saved-searches'
      path: '/saved-searches'
      fullPath: '/saved-searches'
      preLoaderRoute: typeof SavedSearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-requests': {
      id: '/property-requests'
      path: '/property-requests'
      fullPath: '/property-requests'
      preLoaderRoute: typeof PropertyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification-settings': {
      id: '/notification-settings'
      path: '/notification-settings'
      fullPath: '/notification-settings'
      preLoaderRoute: typeof NotificationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-leads': {
      id: '/my-leads'
      path: '/my-leads'
      fullPath: '/my-leads'
      preLoaderRoute: typeof MyLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-requests/new': {
      id: '/property-requests/new'
      path: '/new'
      fullPath: '/property-requests/new'
      preLoaderRoute: typeof PropertyRequestsNewRouteImport
      parentRoute: typeof PropertyRequestsRoute
    }
    '/property-requests/$id': {
      id: '/property-requests/$id'
      path: '/$id'
      fullPath: '/property-requests/$id'
      preLoaderRoute: typeof PropertyRequestsIdRouteImport
      parentRoute: typeof PropertyRequestsRoute
    }
    '/partner/requests': {
      id: '/partner/requests'
      path: '/requests'
      fullPath: '/partner/requests'
      preLoaderRoute: typeof PartnerRequestsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/register': {
      id: '/partner/register'
      path: '/register'
      fullPath: '/partner/register'
      preLoaderRoute: typeof PartnerRegisterRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/lead/new': {
      id: '/lead/new'
      path: '/lead/new'
      fullPath: '/lead/new'
      preLoaderRoute: typeof LeadNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead/$leadId': {
      id: '/lead/$leadId'
      path: '/lead/$leadId'
      fullPath: '/lead/$leadId'
      preLoaderRoute: typeof LeadLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract/$leadId': {
      id: '/contract/$leadId'
      path: '/contract/$leadId'
      fullPath: '/contract/$leadId'
      preLoaderRoute: typeof ContractLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$id': {
      id: '/agent/$id'
      path: '/agent/$id'
      fullPath: '/agent/$id'
      preLoaderRoute: typeof AgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/property-requests': {
      id: '/admin_/property-requests'
      path: '/admin/property-requests'
      fullPath: '/admin/property-requests'
      preLoaderRoute: typeof AdminPropertyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/notifications': {
      id: '/admin_/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/': {
      id: '/property/'
      path: '/property'
      fullPath: '/property/'
      preLoaderRoute: typeof PropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/requests/$id': {
      id: '/partner/requests/$id'
      path: '/$id'
      fullPath: '/partner/requests/$id'
      preLoaderRoute: typeof PartnerRequestsIdRouteImport
      parentRoute: typeof PartnerRequestsRoute
    }
    '/partner/leads/$leadId': {
      id: '/partner/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/partner/leads/$leadId'
      preLoaderRoute: typeof PartnerLeadsLeadIdRouteImport
      parentRoute: typeof PartnerRoute
    }
  }
}

interface PartnerRequestsRouteChildren {
  PartnerRequestsIdRoute: typeof PartnerRequestsIdRoute
}

const PartnerRequestsRouteChildren: PartnerRequestsRouteChildren = {
  PartnerRequestsIdRoute: PartnerRequestsIdRoute,
}

const PartnerRequestsRouteWithChildren = PartnerRequestsRoute._addFileChildren(
  PartnerRequestsRouteChildren,
)

interface PartnerRouteChildren {
  PartnerRegisterRoute: typeof PartnerRegisterRoute
  PartnerRequestsRoute: typeof PartnerRequestsRouteWithChildren
  PartnerLeadsLeadIdRoute: typeof PartnerLeadsLeadIdRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerRegisterRoute: PartnerRegisterRoute,
  PartnerRequestsRoute: PartnerRequestsRouteWithChildren,
  PartnerLeadsLeadIdRoute: PartnerLeadsLeadIdRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

interface PropertyRequestsRouteChildren {
  PropertyRequestsIdRoute: typeof PropertyRequestsIdRoute
  PropertyRequestsNewRoute: typeof PropertyRequestsNewRoute
}

const PropertyRequestsRouteChildren: PropertyRequestsRouteChildren = {
  PropertyRequestsIdRoute: PropertyRequestsIdRoute,
  PropertyRequestsNewRoute: PropertyRequestsNewRoute,
}

const PropertyRequestsRouteWithChildren =
  PropertyRequestsRoute._addFileChildren(PropertyRequestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdvisorRoute: AdvisorRoute,
  AnalyticsRoute: AnalyticsRoute,
  AreasRoute: AreasRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  EstimateRoute: EstimateRoute,
  ImportRoute: ImportRoute,
  MethodologyRoute: MethodologyRoute,
  MyLeadsRoute: MyLeadsRoute,
  NotificationSettingsRoute: NotificationSettingsRoute,
  NotificationsRoute: NotificationsRoute,
  PartnerRoute: PartnerRouteWithChildren,
  PartnersRoute: PartnersRoute,
  PropertyRequestsRoute: PropertyRequestsRouteWithChildren,
  SavedRoute: SavedRoute,
  SavedSearchesRoute: SavedSearchesRoute,
  SearchRoute: SearchRoute,
  PropertyRoute: PropertyRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPropertyRequestsRoute: AdminPropertyRequestsRoute,
  AgentIdRoute: AgentIdRoute,
  ContractLeadIdRoute: ContractLeadIdRoute,
  LeadLeadIdRoute: LeadLeadIdRoute,
  LeadNewRoute: LeadNewRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
